### PR TITLE
Fix for file inconsistencies in file system and main editor

### LINKED ISSUE #73: File inconsistencies
File inconsistencies occur often, usually involving clicking generated SBML and Antimony model files from the model search and then clicking on another file and then clicking back.

Another bug is when double clicking on an editor for a file, clicking on another file, and then clicking back to the first file, the content of the first file will be replaced with the contents of the second file.

### PR DESCRIPTION
**Pull request by lognguyenle**
Attempt to fix #73 and #59

Overview:
- Select interactions result in file data being overwritten or shown incorrectly:
  - Double clicking on a file A in the editor, switching to file B, switching to file A results in file A now containing file B's data
  - Converting or adding new files/models then switching between files results in file content inconsistencies as well
  
Changes:
- In AntimonyEditor component:
  - make sure file is loaded from database with content before the rest of the component is rendered
  - Editor now changes the focused file on the state change of 'selectedFile'
  - Files save only after changes from user
  - On model search, files are added to the database, saved, then switched to in the editor
 
- In main App:
  - SBML and Antimony conversion were complicated, rely on convertAntimonytoSBML and convertSBMLtoAntimony methods instead of processSBML and processAntimony
    - removed sbmlResultHandler, antimonyResultHandler and associated states and lines
   
Tests:
- could not get AWE to build locally
- passes all working tests in `npm run test`

### CODE REVIEW

File: src/components/antimony-editor/AntimonyEditor.tsx [hunk 1]
```diff
@@ -313,24 +345,14 @@ const AntimonyEditor: React.FC<AntimonyEditorProps & { database: IDBPDatabase<My
           monaco.editor.defineTheme("antimonyTheme", antimonyTheme);
           monaco.editor.setTheme("antimonyTheme");
           // Retrieve content and file name from IndexedDB
```
Comment (kevincnguyen) [inline src/components/antimony-editor/AntimonyEditor.tsx:347]: nit: Try to remove any outdated comments or code you commented out to keep the codebase clean. It's often hard to catch though, so no worries!

File: src/components/antimony-editor/AntimonyEditor.tsx [hunk 2]
```diff
@@ -340,17 +362,15 @@ const AntimonyEditor: React.FC<AntimonyEditorProps & { database: IDBPDatabase<My
...
               bracketPairColorization: { enabled: true }, // Enable bracket pair colorization
-              value: content,
+              value: initialContent,
               language: "antimony",
               automaticLayout: true,
               wordWrap: 'on',  // Enable word wrap
               wordWrapColumn: 80,  // Max column width before wrapping
               wrappingIndent: 'same',
             });
             window.antimonyActive = true;
```
Comment (kevincnguyen) [inline src/components/antimony-editor/AntimonyEditor.tsx:372]: nit: I think `window.antimonyActive` can be removed as it is not used for anything anymore.

File: src/App.tsx [hunk 3]
```diff
@@ -133,149 +128,59 @@ const App: React.FC = () => {
...
+    setSelectedFileName(fileName);
   };
 
   /**
    * @description Handles conversion from Antimony to SBML
    */
   const handleConversionAntimony = () => {
     try {
-      if (window.processAntimony) {
-        window.processAntimony();
```
Comment (kevincnguyen) [inline src/App.tsx:149]: To keep the codebase clean, I believe we can remove `processAntimony` and also `processSBML` can be removed from Conversion.js (both in the `root` and `public` folders) and any remaining mentions of them as both methods are not used anymore.

**Review by kevincnguyen — CHANGES_REQUESTED** [review]
I manually tested and built the code and it all seems to work as intended! I also agree with you that the previous SBML and Antimony conversion was complicated, so I like the changes you made. 

Overall, it looks good to me, but I think you can clean up some lines of code before merging!

**Comment by lognguyenle** [comment]
Changes:
- removed leftover and remnant codes and comments (all of them I think)
- removed window.antimonyActive global variable
- removed selectedFileContent and handleConversionSBML from AntimonyEditor props
- rewrote a couple of comments mentioning old methods
- added some null checking for ease of bug-fixing
- added a couple of new comments for certain lines

File: src/App.tsx (hunk 3 above)
Comment (lognguyenle) [reply src/App.tsx:149]: Thanks for the thorough review and feedback! I added the requested changes. Should I feel free to merge?

**Review by kevincnguyen — APPROVED** [review]
Looks good to me! I would wait until Edison reviews this before merging, as I could've missed something.

**Review by Edih112 — APPROVED** [review]
lGTM! Tested manually and the fix seems to work, and the codebase is more concise now which is a huge plus! 

Side note: for `npm run build` to work you need to make the changes to `path.js` described in https://github.com/sys-bio/AntimonyEditor/blob/master/DEV_INSTRUCTIONS/DevInstructions.md (these are just temporary and only needed on deployment/build.
